name: CI do Auth Service

on:
  push:
    branches: [ main ]
    paths:
      - 'auth-service/**'
      - '.github/workflows/auth-service-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'auth-service/**'

jobs:
  build-e-test-auth-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 and Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and Test with Maven
        run: mvn -B verify
        working-directory: ./auth-service